inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

RSpec/NestedGroups:
  Max: 5

Style/Documentation:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

AllCops:
  SuggestExtensions: false
  NewCops: enable

RSpec/MultipleMemoizedHelpers:
  Enabled: false